<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ZeroPlayersOnline</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyTitle>ZeroPlayersOnline</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="SadConsole" />
    <Using Include="SadRogue.Primitives" />
    <Using Include="SadConsole.Console" Alias="Console" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GoRogue" Version="2.6.4" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.4.1" />
    <PackageReference Include="SadConsole.Host.MonoGame" Version="10.10.0" />
    <PackageReference Include="SadConsole.Extended" Version="10.10.0" />
    <PackageReference Include="SadRex" Version="1.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="irrKlang.NET4">
      <HintPath>irrKlang.NET4.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="fonts\CheepicusExtended.font">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="fonts\CheepicusExtended.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="fonts\ThinExtended.font">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="fonts\ThinExtended.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="irrKlang.NET4.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="loginbg.xp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
